apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: lora-multi
spec:
  replicas: 1
  model:
    uri: hf://Qwen/Qwen3-0.6B
    name: Qwen/Qwen3-0.6B
    lora:
      adapters:
        - name: tldr-adapter
          uri: hf://phh/Qwen3-0.6B-TLDR-Lora
        - name: alpaca-adapter
          uri: hf://Threatthriver/qwen3-0.6b-alpaca-lora
      maxAdapters: 2
      maxRank: 64
  router:
    scheduler:
      template:
        imagePullSecrets:
        - name: rhai-pull-secret
        containers:
        - name: main
    route: {}
    gateway: {}
  template:
    imagePullSecrets:
    - name: rhai-pull-secret
    containers:
      - name: main
        env:
          - name: VLLM_ADDITIONAL_ARGS
            value: "--gpu-memory-utilization 0.8"
        resources:
          limits:
            cpu: '2'
            memory: 8Gi
            nvidia.com/gpu: "1"
          requests:
            cpu: '1'
            memory: 4Gi
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 5
